
name: My first workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo "My first action"
      - name: Checkout a repo
        uses: actions/checkout@v4
      - name: List files
        run: ls
      - name: Run Cowsay
        run: cowsay -f dragon "DRAGON HERE..... RUN .. "
      - name: Read Files
        run: cat /etc/hosts
      
