name: Environment Variables Playground
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: "Print the environment variables"
        run: echo  ${{ vars.APP_NAME }}
