name: Muti Jobs in Sequnce
on: push
jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        run: echo "I am job 2"
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: echo "I am job 3"
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "I am job 1"
  job4:
    needs: [job1,job3]
    runs-on: ubuntu-latest
    steps:
      - name: Job 4
        run: echo "I am job 4"
  
