name: Store Workflow Data
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: echo "Hello" > hello.txt
      - name: Upload a file
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./hello.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Download Hello.txt
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Check the contents
        run: cat hello.txt


    
    
